#System Configuration \u2013 Restaurant Management
#Fri Apr 17 13:44:22 GMT+07:00 2026
bank.account=88810102004888
bank.holder=CAO TRONG NGUYEN
bank.name=MB
bank.qr_template=https\://img.vietqr.io/image/%s-%s-compact.png?amount\=%.0f&addInfo\=%s&accountName\=%s
res.address=12 Nguyễn Văn Bảo, Phường 4, Gò Vấp, TP.HCM
res.logo=
res.name=NHÀ HÀNG HẬU
res.phone=0123.456.789
tax.service=5.0
tax.vat=8.0
