#System Configuration \u2013 Restaurant Management
#Mon Apr 20 12:51:13 GMT+07:00 2026
bank.account=0346851496
bank.holder=NGUYEN PHUOC HAU
bank.name=MB
bank.qr_template=https\://img.vietqr.io/image/%s-%s-compact.png?amount\=%.0f&addInfo\=%s&accountName\=%s
res.address=12 Nguyễn Văn Bảo, Phường 4, Gò Vấp, TP.HCM
res.logo=
res.name=NHÀ HÀNG HẬU
res.phone=0123.456.789
tax.service=5.0
tax.vat=8.0
