#System Configuration \u2013 Restaurant Management
#Thu May 28 10:52:53 ICT 2026
bank.account=0346851496
tax.service=0.0
bank.holder=NGUYEN PHUOC HAU
res.phone=0123.456.789
bank.name=MB
res.address=12 Nguyễn Văn Bảo, Phường 4, Gò Vấp, TP.HCM
res.logo=
bank.qr_template=https\://img.vietqr.io/image/%s-%s-compact.png?amount\=%.0f&addInfo\=%s&accountName\=%s
tax.vat=8.0
res.name=NHÀ HÀNG HẬU
